GET http://localhost:8080/microservice/api/v1/notes/

###

###

POST http://localhost:8080/microservice/api/v1/notes/
Content-Type: application/json

{
    "title": "Note 1",
    "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, blanditiis."
}

###
### replace ":noteId" by the current id returned by GET request
PATCH http://localhost:8080/microservice/api/v1/notes/:noteId
Content-Type: application/json

{
    "title": "Note 1 updated",
    "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, blanditiis."
}
