GET http://localhost:8080/microservice/api/v1/tasks/

###

###

POST http://localhost:8080/microservice/api/v1/tasks/
Content-Type: application/json

{
    "title": "Task 1",
    "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, blanditiis."
}

###
### replace ":taskId" by the current id returned by GET request
PATCH http://localhost:8080/microservice/api/v1/tasks/:taskId
Content-Type: application/json

{
    "title": "Task 1 updated",
    "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, blanditiis."
}
